# Copyright (C) 28/1/21 RW Bunney

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from abc import ABC, abstractmethod
from enum import Enum


class Instrument(ABC):
    """
    Abstract base class for the Instrument actor.

    The Instrument is responsible for managing observations and their
    lifecycle. It coordinates with the Scheduler to check ingest capacity,
    start observations, and finalise them once complete.

    Users must subclass this and implement :py:meth:`run` and
    :py:meth:`to_df`.

    Parameters
    ----------
    env : simpy.Environment
        The simulation environment.
    config : ~topsim.core.config.Config
        The parsed simulation configuration.
    planner : ~topsim.core.planner.Planner
        The Planner actor for the simulation.
    scheduler : ~topsim.core.scheduler.Scheduler
        The Scheduler actor for the simulation.

    Notes
    -----
    Recommended decisions in the ``run()`` method:

    1. Check observation readiness:
       ``observation.is_ready(self.env.now, capacity)``

    2. Communicate with Scheduler for ingest capacity:
       ``self.scheduler.check_ingest_capacity(...)``

    3. Start observation and allocate ingest:
       ``self.env.process(self.scheduler.allocate_ingest(...))``

    4. Finalise observation:
       ``observation.status = self.finish_observation(observation)``

    See Also
    --------
    :py:class:`~topsim.user.telescope.Telescope` : Example implementation.
    """

    def __init__(self, env, config, planner, scheduler):
        pass

    @abstractmethod
    def run(self):
        """
        The starting point for the Instrument actor; this will make
        decisions per timestep and then once these decisions have been
        resolved, yield a timeout to indicate a single timestep has passed
        for the Telescope.

        Yields
        ------
        self.env.timeout(x)
            A single simulation timestep of `x` time.
        """

        pass

    @abstractmethod
    def to_df(self):
        """
        Produce a `pandas.DataFrame` of output for the Simulation
        :py:obj:`~topsim.core.monitor.Monitor`.
        Returns
        -------

        """
        pass


class Observation(object):
    """
    Stores information about a single observation.

    An observation has a start time, duration, instrument demand (antenna
    count), associated workflow, and data production rate. During the
    simulation, the observation's plan is generated by the Planner once
    the observation starts on the telescope.

    Parameters
    ----------
    name : str
        Observation name.
    start : int
        Expected start time of the observation.
    duration : int
        Expected duration of the observation (in simulation timesteps).
    demand : int
        Number of antennas/arrays required for the observation.
    workflow : str
        Path to the workflow DAG specification (JSON file).
    data_rate : int
        Incoming data rate produced by the observation per timestep.
    timestep : str, optional
        Unit of simulation time (``'seconds'``, ``'minutes'``, ``'hours'``).
    min_resources : int, optional
        Minimum computing resources required for workflow processing.
    max_resources : int, optional
        Maximum computing resources allowed for workflow processing.

    Attributes
    ----------
    name : str
    est : int
        Expected start time
    ast : int or None
        Actual start time (set during simulation)
    duration : int
    demand : int
    workflow : str
    total_data_size : int
        Accumulated during observation via ``ingest_data_rate * duration``.
    ingest_data_rate : int
    status : RunStatus
        Current observation status (WAITING, RUNNING, FINISHED).
    plan : WorkflowPlan or None
        Workflow plan generated by the Planner once the observation starts.
    """

    def __init__(self, name, start, duration, demand, workflow,
                 data_rate, timestep='seconds',min_resources=-1,max_resources=-1):

        # TODO change to self.id
        self.name = name
        self.buffer_id = 0
        self.cluster_id = 'default'
        # self.start = start
        self.est = start
        self.ast = None
        self.duration = duration
        self.demand = demand
        self.workflow = workflow
        self.total_data_size = 0
        self.ingest_data_rate = data_rate
        self.timestep = timestep
        self.status = RunStatus.WAITING
        self.min_resources = min_resources
        self.max_resources = max_resources

        self.plan = None

    def is_ready(self, current_time, capacity):
        """

        Parameters
        ----------
        current_time: int
            The current simulation time (Simpy.env.now)
        capacity : int
            Current capacity of the telescope at this time

        Returns
        -------
        True if telescope has capacity, and the observation is scheduled to
        start from now

        False if telescope does not have capacity

        """
        if self.est <= current_time \
                and self.demand <= capacity \
                and self.status is RunStatus.WAITING:
            return True
        else:
            return False

    def is_finished(self, current_time, telescope_status):
        """
        Check if the observation has finished on the telescope.
        Parameters
        ----------
        current_time
        telescope_status

        Returns
        -------

        """
        if self.ast is None:
            return False
        elif current_time >= self.ast + self.duration \
                and telescope_status \
                and (self.status is not RunStatus.FINISHED):
            return True
        else:
            return False


class RunStatus(str, Enum):
    """
    The status of an observation
    """
    WAITING = 'WAITING'
    RUNNING = 'RUNNING'
    FINISHED = 'FINISHED'
