name: Python package

on: [push]

jobs:
  unittests:
    name: Run unit tests for TOpSim
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.10"
          - python-version:  "3.11"
          - python-version:  "3.12"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -U pip setuptools wheel coveralls pytest pytest-cov

      - name: Install TopSim
        run: pip install .

      - name: Run unittests with coverage
        run: pytest . --cov

      - name: Upload to Coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
